name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@v2
      - name: run test
        run: |
         python -m unittest test.py
        #test/Serveur/test.py

        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
